services:
  - type: web
    name: ricas-papas-mary
    runtime: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: localhost,127.0.0.1,ricas-papas-mary.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://localhost,https://127.0.0.1,https://ricas-papas-mary.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: ricas-papas-mary-db
          property: connectionString
      - key: GOOGLE_MAPS_API_KEY
        sync: false

databases:
  - name: ricas-papas-mary-db
    databaseName: ricapapas_db
    user: ricapapas_user
